### ISSUE TITLE
QA CheckList

### ISSUE THREAD

**Issue by jopiniano** [jopiniano/QA-Assignment-2#22]
Browser Optimized
- [x] Chrome
- [x] Firefox
- [x] Safari
Image Optimized 
- [x] ~300KB
- [x] Alt is filled in
 Device Optimized
- [x] iPhone 12
- [x] Mac OS 
- [x] Windows 10
- [x] iPad Pro 12.9
Projects
- [x] Grammar + Spell check
- [x] The content matches the topic of the site
- [x] Proper Layout 
- [x] No broken links
